# docker run --name fssdb -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres
# docker-compose.yml
version: '3'
services:
  database:
    image: fssdb
    build:
      context: dockerfile/fssdb
      dockerfile: Dockerfile
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: fssdb
    env_file:
      - dockerfile/fssdb/database.env # configure postgres
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
    external: false
