DROP TABLE IF EXISTS NOTICES CASCADE;
DROP TABLE IF EXISTS USERS_ROLES CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS
(
    USER_ID  BIGINT                NOT NULL GENERATED ALWAYS AS IDENTITY,
    PASSWORD VARCHAR(255)          NOT NULL,
    USERNAME VARCHAR(255)          NOT NULL UNIQUE,
    ENABLED  BOOLEAN DEFAULT FALSE NOT NULL,
    TO_DELETE BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE ROLES
(
    ROLE_ID   BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY,
    ROLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USERS_ROLES
(
    USER_ROLES_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USER_ID       BIGINT NOT NULL,
    ROLE_ID       BIGINT NOT NULL,
    PRIMARY KEY (USER_ROLES_ID),
    CONSTRAINT USERS_ROLES_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT USERS_ROLES_FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);

CREATE TABLE NOTICES
(
    NOTICE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    TITLE         VARCHAR(255) NOT NULL,
    TEXT_CONTENT       TEXT NOT NULL,
    PUBLICATION_DATE   TIMESTAMP NOT NULL,
    EXPIRATION_DATE    DATE NOT NULL,
    AUTHOR        BIGINT NOT NULL,
    PRIMARY KEY (NOTICE_ID),
    CONSTRAINT NOTICES_FK_USER FOREIGN KEY (AUTHOR) REFERENCES USERS (USER_ID)
);


-- INSERT ROLES
INSERT INTO roles (role_id, role_name) VALUES (DEFAULT, 'ROLE_USER');
INSERT INTO roles (role_id, role_name) VALUES (DEFAULT,'ROLE_ADMIN');

-- INSERT USERS
--password:secret
INSERT INTO users (user_id, enabled, password, username)
VALUES (DEFAULT, true,'$2a$10$lTBRa6LF1UR5yoL7K7bIzOkWdn/BFB4h7hxy97CCcc/sKyHfDMLPS', 'user');
INSERT INTO users (user_id, enabled, password, username)
VALUES (DEFAULT, true,'$2a$10$lTBRa6LF1UR5yoL7K7bIzOkWdn/BFB4h7hxy97CCcc/sKyHfDMLPS', 'admin');
INSERT INTO users (user_id, enabled, password, username)
VALUES (DEFAULT, true,'$2a$10$lTBRa6LF1UR5yoL7K7bIzOkWdn/BFB4h7hxy97CCcc/sKyHfDMLPS', 'super');
INSERT INTO users (user_id, enabled, password, username)
VALUES (DEFAULT, true,'$2a$10$lTBRa6LF1UR5yoL7K7bIzOkWdn/BFB4h7hxy97CCcc/sKyHfDMLPS', 'none');


INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 2);