TRUNCATE public.notices RESTART IDENTITY CASCADE ;
TRUNCATE public.users RESTART IDENTITY CASCADE ;
TRUNCATE public.roles RESTART IDENTITY CASCADE ;
TRUNCATE public.users_roles RESTART IDENTITY CASCADE ;